export const FETCH_COLOR_REQUEST = 'FETCH_COLOR_REQUEST'
export const FETCH_COLOR_FAILURE = 'FETCH_COLOR_FAILURE'
export const FETCH_COLOR_SUCCESS = 'FETCH_COLO_SUCCESS'
export const ADD_TODO = 'ADD_TODO'
export const ADD_COLOR = 'ADD_COLOR'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const ADD_LIST = 'ADD_LIST'
export const TOGGLE_LIST = 'TOGGLE_LIST'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}
